#!/usr/bin/env python3
"""Upload the enriched audio dataset to the HF dataset repo.

After Tatoeba downloads + Pimsleur extraction + preprocess.py have all
finished, the local `data/audio/<lang>/` directories contain:
  - <hash>.wav         (FLEURS clips)
  - tatoeba_<id>.wav   (Tatoeba clips)
  - pimsleur_*.wav     (Pimsleur clips)
  - manifest.jsonl     (combined entries with source field)
  - phonemes.jsonl     (regenerated by preprocess.py)
  - vad.jsonl          (optional; only present for sources that have VAD probs)

This script uses `huggingface_hub.HfApi.upload_folder` to mirror those
directories to `anchpop/lexide-pronunciation-audio` — which is what the
sky_*.yaml training yamls download at runtime.

Run after all data prep is done and you're ready to swap the dataset
that the next sky launch will pull.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from huggingface_hub import HfApi, login

DEFAULT_REPO = "anchpop/lexide-pronunciation-audio"


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--audio-root", type=Path,
                        default=Path(__file__).resolve().parent.parent / "data" / "audio")
    parser.add_argument("--repo", default=DEFAULT_REPO,
                        help=f"HF dataset repo (default: {DEFAULT_REPO})")
    parser.add_argument("--env-file", type=Path, default=Path(".env"))
    parser.add_argument("--commit-message", default="Add Tatoeba + Pimsleur clips")
    parser.add_argument("--dry-run", action="store_true",
                        help="List what would be uploaded without actually uploading.")
    args = parser.parse_args()
    load_env_file(args.env_file)

    if not args.audio_root.exists():
        sys.exit(f"Audio root not found: {args.audio_root}")

    token = os.environ.get("HF_TOKEN")
    if not token and not args.dry_run:
        raise SystemExit("HF_TOKEN is not set")

    total_files = 0
    total_bytes = 0
    by_lang: dict[str, dict[str, int]] = {}
    for lang_dir in sorted(args.audio_root.iterdir()):
        if not lang_dir.is_dir():
            continue
        lang = lang_dir.name
        stats = {"fleurs": 0, "tatoeba": 0, "pimsleur": 0, "other": 0}
        for f in lang_dir.iterdir():
            if not f.is_file():
                continue
            total_files += 1
            total_bytes += f.stat().st_size
            if f.name.startswith("tatoeba_"):
                stats["tatoeba"] += 1
            elif f.name.startswith("pimsleur_"):
                stats["pimsleur"] += 1
            elif f.suffix == ".wav":
                stats["fleurs"] += 1
            else:
                stats["other"] += 1
        by_lang[lang] = stats

    print(f"Found {total_files} files, {total_bytes / 1e9:.2f} GB total")
    for lang, s in sorted(by_lang.items()):
        print(f"  {lang}: fleurs={s['fleurs']} tatoeba={s['tatoeba']} "
              f"pimsleur={s['pimsleur']} other(jsonl/etc)={s['other']}")

    if args.dry_run:
        return

    login(token=token, add_to_git_credential=False)
    api = HfApi()
    api.create_repo(args.repo, repo_type="dataset", exist_ok=True)

    print(f"\nUploading {args.audio_root} → {args.repo} ...")
    api.upload_folder(
        folder_path=str(args.audio_root),
        repo_id=args.repo,
        repo_type="dataset",
        commit_message=args.commit_message,
    )
    print("Done.")


if __name__ == "__main__":
    main()
